/* automatically generated by rust-bindgen 0.72.1 */

pub const __bool_true_false_are_defined: u32 = 1;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const _STDINT_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC2Y: u32 = 0;
pub const __GLIBC_USE_ISOC23: u32 = 0;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __TIMESIZE: u32 = 64;
pub const __USE_TIME_BITS64: u32 = 1;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const __GLIBC_USE_C23_STRTOL: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 41;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C23: u32 = 0;
pub const __GLIBC_USE_IEC_60559_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C23: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const _BITS_TYPES_H: u32 = 1;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __OFF_T_MATCHES_OFF64_T: u32 = 1;
pub const __INO_T_MATCHES_INO64_T: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
pub const __STATFS_MATCHES_STATFS64: u32 = 1;
pub const __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64: u32 = 1;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_TIME64_H: u32 = 1;
pub const _BITS_WCHAR_H: u32 = 1;
pub const _BITS_STDINT_INTN_H: u32 = 1;
pub const _BITS_STDINT_UINTN_H: u32 = 1;
pub const _BITS_STDINT_LEAST_H: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i64 = -9223372036854775808;
pub const INT_FAST32_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u64 = 9223372036854775807;
pub const INT_FAST32_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: i32 = -1;
pub const UINT_FAST32_MAX: i32 = -1;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const UINTPTR_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIZE_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub type __u_char = ::core::ffi::c_uchar;
pub type __u_short = ::core::ffi::c_ushort;
pub type __u_int = ::core::ffi::c_uint;
pub type __u_long = ::core::ffi::c_ulong;
pub type __int8_t = ::core::ffi::c_schar;
pub type __uint8_t = ::core::ffi::c_uchar;
pub type __int16_t = ::core::ffi::c_short;
pub type __uint16_t = ::core::ffi::c_ushort;
pub type __int32_t = ::core::ffi::c_int;
pub type __uint32_t = ::core::ffi::c_uint;
pub type __int64_t = ::core::ffi::c_long;
pub type __uint64_t = ::core::ffi::c_ulong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __quad_t = ::core::ffi::c_long;
pub type __u_quad_t = ::core::ffi::c_ulong;
pub type __intmax_t = ::core::ffi::c_long;
pub type __uintmax_t = ::core::ffi::c_ulong;
pub type __dev_t = ::core::ffi::c_ulong;
pub type __uid_t = ::core::ffi::c_uint;
pub type __gid_t = ::core::ffi::c_uint;
pub type __ino_t = ::core::ffi::c_ulong;
pub type __ino64_t = ::core::ffi::c_ulong;
pub type __mode_t = ::core::ffi::c_uint;
pub type __nlink_t = ::core::ffi::c_ulong;
pub type __off_t = ::core::ffi::c_long;
pub type __off64_t = ::core::ffi::c_long;
pub type __pid_t = ::core::ffi::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [::core::ffi::c_int; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __fsid_t"][::core::mem::size_of::<__fsid_t>() - 8usize];
    ["Alignment of __fsid_t"][::core::mem::align_of::<__fsid_t>() - 4usize];
    ["Offset of field: __fsid_t::__val"][::core::mem::offset_of!(__fsid_t, __val) - 0usize];
};
pub type __clock_t = ::core::ffi::c_long;
pub type __rlim_t = ::core::ffi::c_ulong;
pub type __rlim64_t = ::core::ffi::c_ulong;
pub type __id_t = ::core::ffi::c_uint;
pub type __time_t = ::core::ffi::c_long;
pub type __useconds_t = ::core::ffi::c_uint;
pub type __suseconds_t = ::core::ffi::c_long;
pub type __suseconds64_t = ::core::ffi::c_long;
pub type __daddr_t = ::core::ffi::c_int;
pub type __key_t = ::core::ffi::c_int;
pub type __clockid_t = ::core::ffi::c_int;
pub type __timer_t = *mut ::core::ffi::c_void;
pub type __blksize_t = ::core::ffi::c_long;
pub type __blkcnt_t = ::core::ffi::c_long;
pub type __blkcnt64_t = ::core::ffi::c_long;
pub type __fsblkcnt_t = ::core::ffi::c_ulong;
pub type __fsblkcnt64_t = ::core::ffi::c_ulong;
pub type __fsfilcnt_t = ::core::ffi::c_ulong;
pub type __fsfilcnt64_t = ::core::ffi::c_ulong;
pub type __fsword_t = ::core::ffi::c_long;
pub type __ssize_t = ::core::ffi::c_long;
pub type __syscall_slong_t = ::core::ffi::c_long;
pub type __syscall_ulong_t = ::core::ffi::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut ::core::ffi::c_char;
pub type __intptr_t = ::core::ffi::c_long;
pub type __socklen_t = ::core::ffi::c_uint;
pub type __sig_atomic_t = ::core::ffi::c_int;
pub type int_least8_t = __int_least8_t;
pub type int_least16_t = __int_least16_t;
pub type int_least32_t = __int_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least8_t = __uint_least8_t;
pub type uint_least16_t = __uint_least16_t;
pub type uint_least32_t = __uint_least32_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = ::core::ffi::c_schar;
pub type int_fast16_t = ::core::ffi::c_long;
pub type int_fast32_t = ::core::ffi::c_long;
pub type int_fast64_t = ::core::ffi::c_long;
pub type uint_fast8_t = ::core::ffi::c_uchar;
pub type uint_fast16_t = ::core::ffi::c_ulong;
pub type uint_fast32_t = ::core::ffi::c_ulong;
pub type uint_fast64_t = ::core::ffi::c_ulong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub type GFSDK_Aftermath_Version = u32;
pub const GFSDK_Aftermath_Version_GFSDK_Aftermath_Version_API: GFSDK_Aftermath_Version = 538;
pub type GFSDK_Aftermath_Result = u32;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_Success: GFSDK_Aftermath_Result = 1;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_NotAvailable: GFSDK_Aftermath_Result = 2;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_Fail: GFSDK_Aftermath_Result = 3134193664;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_VersionMismatch:
    GFSDK_Aftermath_Result = 3134193665;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_NotInitialized:
    GFSDK_Aftermath_Result = 3134193666;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_InvalidAdapter:
    GFSDK_Aftermath_Result = 3134193667;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_InvalidParameter:
    GFSDK_Aftermath_Result = 3134193668;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_Unknown: GFSDK_Aftermath_Result =
    3134193669;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_ApiError: GFSDK_Aftermath_Result =
    3134193670;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_NvApiIncompatible:
    GFSDK_Aftermath_Result = 3134193671;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_GettingContextDataWithNewCommandList : GFSDK_Aftermath_Result = 3134193672 ;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_AlreadyInitialized:
    GFSDK_Aftermath_Result = 3134193673;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_D3DDebugLayerNotCompatible:
    GFSDK_Aftermath_Result = 3134193674;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_DriverInitFailed:
    GFSDK_Aftermath_Result = 3134193675;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_DriverVersionNotSupported:
    GFSDK_Aftermath_Result = 3134193676;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_OutOfMemory: GFSDK_Aftermath_Result =
    3134193677;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_GetDataOnBundle:
    GFSDK_Aftermath_Result = 3134193678;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_GetDataOnDeferredContext:
    GFSDK_Aftermath_Result = 3134193679;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_FeatureNotEnabled:
    GFSDK_Aftermath_Result = 3134193680;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_NoResourcesRegistered:
    GFSDK_Aftermath_Result = 3134193681;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_ThisResourceNeverRegistered:
    GFSDK_Aftermath_Result = 3134193682;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_NotSupportedInUWP:
    GFSDK_Aftermath_Result = 3134193683;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_D3dDllNotSupported:
    GFSDK_Aftermath_Result = 3134193684;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_D3dDllInterceptionNotSupported:
    GFSDK_Aftermath_Result = 3134193685;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_Disabled: GFSDK_Aftermath_Result =
    3134193686;
pub const GFSDK_Aftermath_Result_GFSDK_Aftermath_Result_FAIL_NotSupportedOnContext:
    GFSDK_Aftermath_Result = 3134193687;
pub type GFSDK_Aftermath_Context_Status = u32;
pub const GFSDK_Aftermath_Context_Status_GFSDK_Aftermath_Context_Status_NotStarted:
    GFSDK_Aftermath_Context_Status = 0;
pub const GFSDK_Aftermath_Context_Status_GFSDK_Aftermath_Context_Status_Executing:
    GFSDK_Aftermath_Context_Status = 1;
pub const GFSDK_Aftermath_Context_Status_GFSDK_Aftermath_Context_Status_Finished:
    GFSDK_Aftermath_Context_Status = 2;
pub const GFSDK_Aftermath_Context_Status_GFSDK_Aftermath_Context_Status_Invalid:
    GFSDK_Aftermath_Context_Status = 3;
pub type GFSDK_Aftermath_Device_Status = u32;
pub const GFSDK_Aftermath_Device_Status_GFSDK_Aftermath_Device_Status_Active:
    GFSDK_Aftermath_Device_Status = 0;
pub const GFSDK_Aftermath_Device_Status_GFSDK_Aftermath_Device_Status_Timeout:
    GFSDK_Aftermath_Device_Status = 1;
pub const GFSDK_Aftermath_Device_Status_GFSDK_Aftermath_Device_Status_OutOfMemory:
    GFSDK_Aftermath_Device_Status = 2;
pub const GFSDK_Aftermath_Device_Status_GFSDK_Aftermath_Device_Status_PageFault:
    GFSDK_Aftermath_Device_Status = 3;
pub const GFSDK_Aftermath_Device_Status_GFSDK_Aftermath_Device_Status_Stopped:
    GFSDK_Aftermath_Device_Status = 4;
pub const GFSDK_Aftermath_Device_Status_GFSDK_Aftermath_Device_Status_Reset:
    GFSDK_Aftermath_Device_Status = 5;
pub const GFSDK_Aftermath_Device_Status_GFSDK_Aftermath_Device_Status_Unknown:
    GFSDK_Aftermath_Device_Status = 6;
pub const GFSDK_Aftermath_Device_Status_GFSDK_Aftermath_Device_Status_DmaFault:
    GFSDK_Aftermath_Device_Status = 7;
pub const GFSDK_Aftermath_Device_Status_GFSDK_Aftermath_Device_Status_DeviceRemovedNoGpuFault:
    GFSDK_Aftermath_Device_Status = 8;
pub type GFSDK_Aftermath_FeatureFlags = u32;
pub const GFSDK_Aftermath_FeatureFlags_GFSDK_Aftermath_FeatureFlags_Minimum:
    GFSDK_Aftermath_FeatureFlags = 0;
pub const GFSDK_Aftermath_FeatureFlags_GFSDK_Aftermath_FeatureFlags_EnableMarkers:
    GFSDK_Aftermath_FeatureFlags = 1;
pub const GFSDK_Aftermath_FeatureFlags_GFSDK_Aftermath_FeatureFlags_EnableResourceTracking:
    GFSDK_Aftermath_FeatureFlags = 2;
pub const GFSDK_Aftermath_FeatureFlags_GFSDK_Aftermath_FeatureFlags_CallStackCapturing:
    GFSDK_Aftermath_FeatureFlags = 1073741824;
pub const GFSDK_Aftermath_FeatureFlags_GFSDK_Aftermath_FeatureFlags_GenerateShaderDebugInfo:
    GFSDK_Aftermath_FeatureFlags = 8;
pub const GFSDK_Aftermath_FeatureFlags_GFSDK_Aftermath_FeatureFlags_EnableShaderErrorReporting:
    GFSDK_Aftermath_FeatureFlags = 16;
pub type GFSDK_Aftermath_GpuCrashDumpWatchedApiFlags = u32;
pub const GFSDK_Aftermath_GpuCrashDumpWatchedApiFlags_GFSDK_Aftermath_GpuCrashDumpWatchedApiFlags_None : GFSDK_Aftermath_GpuCrashDumpWatchedApiFlags = 0 ;
pub const GFSDK_Aftermath_GpuCrashDumpWatchedApiFlags_GFSDK_Aftermath_GpuCrashDumpWatchedApiFlags_DX : GFSDK_Aftermath_GpuCrashDumpWatchedApiFlags = 1 ;
pub const GFSDK_Aftermath_GpuCrashDumpWatchedApiFlags_GFSDK_Aftermath_GpuCrashDumpWatchedApiFlags_Vulkan : GFSDK_Aftermath_GpuCrashDumpWatchedApiFlags = 2 ;
pub type GFSDK_Aftermath_GpuCrashDumpFeatureFlags = u32;
pub const GFSDK_Aftermath_GpuCrashDumpFeatureFlags_GFSDK_Aftermath_GpuCrashDumpFeatureFlags_Default : GFSDK_Aftermath_GpuCrashDumpFeatureFlags = 0 ;
pub const GFSDK_Aftermath_GpuCrashDumpFeatureFlags_GFSDK_Aftermath_GpuCrashDumpFeatureFlags_DeferDebugInfoCallbacks : GFSDK_Aftermath_GpuCrashDumpFeatureFlags = 1 ;
pub type GFSDK_Aftermath_GpuCrashDumpDescriptionKey = u32;
pub const GFSDK_Aftermath_GpuCrashDumpDescriptionKey_GFSDK_Aftermath_GpuCrashDumpDescriptionKey_ApplicationName : GFSDK_Aftermath_GpuCrashDumpDescriptionKey = 1 ;
pub const GFSDK_Aftermath_GpuCrashDumpDescriptionKey_GFSDK_Aftermath_GpuCrashDumpDescriptionKey_ApplicationVersion : GFSDK_Aftermath_GpuCrashDumpDescriptionKey = 2 ;
pub const GFSDK_Aftermath_GpuCrashDumpDescriptionKey_GFSDK_Aftermath_GpuCrashDumpDescriptionKey_UserDefined : GFSDK_Aftermath_GpuCrashDumpDescriptionKey = 65536 ;
pub type GFSDK_Aftermath_CrashDump_Status = u32;
pub const GFSDK_Aftermath_CrashDump_Status_GFSDK_Aftermath_CrashDump_Status_NotStarted:
    GFSDK_Aftermath_CrashDump_Status = 0;
pub const GFSDK_Aftermath_CrashDump_Status_GFSDK_Aftermath_CrashDump_Status_CollectingData:
    GFSDK_Aftermath_CrashDump_Status = 1;
pub const GFSDK_Aftermath_CrashDump_Status_GFSDK_Aftermath_CrashDump_Status_CollectingDataFailed:
    GFSDK_Aftermath_CrashDump_Status = 2;
pub const GFSDK_Aftermath_CrashDump_Status_GFSDK_Aftermath_CrashDump_Status_InvokingCallback:
    GFSDK_Aftermath_CrashDump_Status = 3;
pub const GFSDK_Aftermath_CrashDump_Status_GFSDK_Aftermath_CrashDump_Status_Finished:
    GFSDK_Aftermath_CrashDump_Status = 4;
pub const GFSDK_Aftermath_CrashDump_Status_GFSDK_Aftermath_CrashDump_Status_Unknown:
    GFSDK_Aftermath_CrashDump_Status = 5;
pub type PFN_GFSDK_Aftermath_AddGpuCrashDumpDescription =
    ::core::option::Option<unsafe extern "C" fn(key: u32, value: *const ::core::ffi::c_char)>;
pub type PFN_GFSDK_Aftermath_GpuCrashDumpCb = ::core::option::Option<
    unsafe extern "C" fn(
        pGpuCrashDump: *const ::core::ffi::c_void,
        gpuCrashDumpSize: u32,
        pUserData: *mut ::core::ffi::c_void,
    ),
>;
pub type PFN_GFSDK_Aftermath_ShaderDebugInfoCb = ::core::option::Option<
    unsafe extern "C" fn(
        pShaderDebugInfo: *const ::core::ffi::c_void,
        shaderDebugInfoSize: u32,
        pUserData: *mut ::core::ffi::c_void,
    ),
>;
pub type PFN_GFSDK_Aftermath_GpuCrashDumpDescriptionCb = ::core::option::Option<
    unsafe extern "C" fn(
        addValue: PFN_GFSDK_Aftermath_AddGpuCrashDumpDescription,
        pUserData: *mut ::core::ffi::c_void,
    ),
>;
pub type PFN_GFSDK_Aftermath_ResolveMarker = ::core::option::Option<
    unsafe extern "C" fn(
        pResolvedMarkerData: *const ::core::ffi::c_void,
        resolvedMarkerDataSize: u32,
    ),
>;
pub type PFN_GFSDK_Aftermath_ResolveMarkerCb = ::core::option::Option<
    unsafe extern "C" fn(
        pMarkerData: *const ::core::ffi::c_void,
        markerDataSize: u32,
        pUserData: *mut ::core::ffi::c_void,
        resolveMarker: PFN_GFSDK_Aftermath_ResolveMarker,
    ),
>;
unsafe extern "C" {
    pub fn GFSDK_Aftermath_EnableGpuCrashDumps(
        apiVersion: GFSDK_Aftermath_Version,
        watchedApis: u32,
        flags: u32,
        gpuCrashDumpCb: PFN_GFSDK_Aftermath_GpuCrashDumpCb,
        shaderDebugInfoCb: PFN_GFSDK_Aftermath_ShaderDebugInfoCb,
        descriptionCb: PFN_GFSDK_Aftermath_GpuCrashDumpDescriptionCb,
        resolveMarkerCb: PFN_GFSDK_Aftermath_ResolveMarkerCb,
        pUserData: *mut ::core::ffi::c_void,
    ) -> GFSDK_Aftermath_Result;
}
unsafe extern "C" {
    pub fn GFSDK_Aftermath_DisableGpuCrashDumps() -> GFSDK_Aftermath_Result;
}
unsafe extern "C" {
    pub fn GFSDK_Aftermath_GetCrashDumpStatus(
        pOutStatus: *mut GFSDK_Aftermath_CrashDump_Status,
    ) -> GFSDK_Aftermath_Result;
}
pub type PFN_GFSDK_Aftermath_EnableGpuCrashDumps = ::core::option::Option<
    unsafe extern "C" fn(
        apiVersion: GFSDK_Aftermath_Version,
        watchedApis: u32,
        flags: u32,
        gpuCrashDumpCb: PFN_GFSDK_Aftermath_GpuCrashDumpCb,
        shaderDebugInfoCb: PFN_GFSDK_Aftermath_ShaderDebugInfoCb,
        descriptionCb: PFN_GFSDK_Aftermath_GpuCrashDumpDescriptionCb,
        resolveMarkerCb: PFN_GFSDK_Aftermath_ResolveMarkerCb,
        pUserData: *mut ::core::ffi::c_void,
    ) -> GFSDK_Aftermath_Result,
>;
pub type PFN_GFSDK_Aftermath_DisableGpuCrashDumps =
    ::core::option::Option<unsafe extern "C" fn() -> GFSDK_Aftermath_Result>;
pub type PFN_GFSDK_Aftermath_GetCrashDumpStatus = ::core::option::Option<
    unsafe extern "C" fn(
        pOutStatus: *mut GFSDK_Aftermath_CrashDump_Status,
    ) -> GFSDK_Aftermath_Result,
>;
pub const GFSDK_Aftermath_MAX_STRING_LENGTH: _bindgen_ty_1 = 127;
pub type _bindgen_ty_1 = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GFSDK_Aftermath_ShaderDebugInfoIdentifier {
    pub id: [u64; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_ShaderDebugInfoIdentifier"]
        [::core::mem::size_of::<GFSDK_Aftermath_ShaderDebugInfoIdentifier>() - 16usize];
    ["Alignment of GFSDK_Aftermath_ShaderDebugInfoIdentifier"]
        [::core::mem::align_of::<GFSDK_Aftermath_ShaderDebugInfoIdentifier>() - 8usize];
    ["Offset of field: GFSDK_Aftermath_ShaderDebugInfoIdentifier::id"]
        [::core::mem::offset_of!(GFSDK_Aftermath_ShaderDebugInfoIdentifier, id) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GFSDK_Aftermath_ShaderBinaryHash {
    pub hash: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_ShaderBinaryHash"]
        [::core::mem::size_of::<GFSDK_Aftermath_ShaderBinaryHash>() - 8usize];
    ["Alignment of GFSDK_Aftermath_ShaderBinaryHash"]
        [::core::mem::align_of::<GFSDK_Aftermath_ShaderBinaryHash>() - 8usize];
    ["Offset of field: GFSDK_Aftermath_ShaderBinaryHash::hash"]
        [::core::mem::offset_of!(GFSDK_Aftermath_ShaderBinaryHash, hash) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GFSDK_Aftermath_ShaderDebugName {
    pub name: [::core::ffi::c_char; 128usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_ShaderDebugName"]
        [::core::mem::size_of::<GFSDK_Aftermath_ShaderDebugName>() - 128usize];
    ["Alignment of GFSDK_Aftermath_ShaderDebugName"]
        [::core::mem::align_of::<GFSDK_Aftermath_ShaderDebugName>() - 1usize];
    ["Offset of field: GFSDK_Aftermath_ShaderDebugName::name"]
        [::core::mem::offset_of!(GFSDK_Aftermath_ShaderDebugName, name) - 0usize];
};
pub type GFSDK_Aftermath_GraphicsApi = u32;
pub const GFSDK_Aftermath_GraphicsApi_GFSDK_Aftermath_GraphicsApi_Unknown:
    GFSDK_Aftermath_GraphicsApi = 0;
pub const GFSDK_Aftermath_GraphicsApi_GFSDK_Aftermath_GraphicsApi_D3D_10_0:
    GFSDK_Aftermath_GraphicsApi = 1;
pub const GFSDK_Aftermath_GraphicsApi_GFSDK_Aftermath_GraphicsApi_D3D_10_1:
    GFSDK_Aftermath_GraphicsApi = 2;
pub const GFSDK_Aftermath_GraphicsApi_GFSDK_Aftermath_GraphicsApi_D3D_11_0:
    GFSDK_Aftermath_GraphicsApi = 3;
pub const GFSDK_Aftermath_GraphicsApi_GFSDK_Aftermath_GraphicsApi_D3D_11_1:
    GFSDK_Aftermath_GraphicsApi = 4;
pub const GFSDK_Aftermath_GraphicsApi_GFSDK_Aftermath_GraphicsApi_D3D_11_2:
    GFSDK_Aftermath_GraphicsApi = 5;
pub const GFSDK_Aftermath_GraphicsApi_GFSDK_Aftermath_GraphicsApi_D3D_12_0:
    GFSDK_Aftermath_GraphicsApi = 6;
pub const GFSDK_Aftermath_GraphicsApi_GFSDK_Aftermath_GraphicsApi_Vulkan:
    GFSDK_Aftermath_GraphicsApi = 7;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GFSDK_Aftermath_GpuCrashDump_BaseInfo {
    pub applicationName: [::core::ffi::c_char; 128usize],
    pub creationDate: [::core::ffi::c_char; 128usize],
    pub creationTickCount: u32,
    pub pid: u32,
    pub graphicsApi: GFSDK_Aftermath_GraphicsApi,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_GpuCrashDump_BaseInfo"]
        [::core::mem::size_of::<GFSDK_Aftermath_GpuCrashDump_BaseInfo>() - 268usize];
    ["Alignment of GFSDK_Aftermath_GpuCrashDump_BaseInfo"]
        [::core::mem::align_of::<GFSDK_Aftermath_GpuCrashDump_BaseInfo>() - 4usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_BaseInfo::applicationName"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_BaseInfo, applicationName) - 0usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_BaseInfo::creationDate"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_BaseInfo, creationDate) - 128usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_BaseInfo::creationTickCount"][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_BaseInfo,
        creationTickCount
    ) - 256usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_BaseInfo::pid"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_BaseInfo, pid) - 260usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_BaseInfo::graphicsApi"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_BaseInfo, graphicsApi) - 264usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct GFSDK_Aftermath_GpuCrashDump_DeviceInfo {
    pub status: GFSDK_Aftermath_Device_Status,
    pub __bindgen_anon_1: GFSDK_Aftermath_GpuCrashDump_DeviceInfo__bindgen_ty_1,
    pub __bindgen_anon_2: GFSDK_Aftermath_GpuCrashDump_DeviceInfo__bindgen_ty_2,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union GFSDK_Aftermath_GpuCrashDump_DeviceInfo__bindgen_ty_1 {
    pub adapterReset: bool,
    pub bool_align_adapterReset: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_GpuCrashDump_DeviceInfo__bindgen_ty_1"]
        [::core::mem::size_of::<GFSDK_Aftermath_GpuCrashDump_DeviceInfo__bindgen_ty_1>() - 4usize];
    ["Alignment of GFSDK_Aftermath_GpuCrashDump_DeviceInfo__bindgen_ty_1"]
        [::core::mem::align_of::<GFSDK_Aftermath_GpuCrashDump_DeviceInfo__bindgen_ty_1>() - 4usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_DeviceInfo__bindgen_ty_1::adapterReset"][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_DeviceInfo__bindgen_ty_1,
        adapterReset
    )
        - 0usize];
    [
        "Offset of field: GFSDK_Aftermath_GpuCrashDump_DeviceInfo__bindgen_ty_1::bool_align_adapterReset",
    ][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_DeviceInfo__bindgen_ty_1,
        bool_align_adapterReset
    ) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union GFSDK_Aftermath_GpuCrashDump_DeviceInfo__bindgen_ty_2 {
    pub engineReset: bool,
    pub bool_align_engineReset: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_GpuCrashDump_DeviceInfo__bindgen_ty_2"]
        [::core::mem::size_of::<GFSDK_Aftermath_GpuCrashDump_DeviceInfo__bindgen_ty_2>() - 4usize];
    ["Alignment of GFSDK_Aftermath_GpuCrashDump_DeviceInfo__bindgen_ty_2"]
        [::core::mem::align_of::<GFSDK_Aftermath_GpuCrashDump_DeviceInfo__bindgen_ty_2>() - 4usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_DeviceInfo__bindgen_ty_2::engineReset"][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_DeviceInfo__bindgen_ty_2,
        engineReset
    )
        - 0usize];
    [
        "Offset of field: GFSDK_Aftermath_GpuCrashDump_DeviceInfo__bindgen_ty_2::bool_align_engineReset",
    ][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_DeviceInfo__bindgen_ty_2,
        bool_align_engineReset
    ) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_GpuCrashDump_DeviceInfo"]
        [::core::mem::size_of::<GFSDK_Aftermath_GpuCrashDump_DeviceInfo>() - 12usize];
    ["Alignment of GFSDK_Aftermath_GpuCrashDump_DeviceInfo"]
        [::core::mem::align_of::<GFSDK_Aftermath_GpuCrashDump_DeviceInfo>() - 4usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_DeviceInfo::status"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_DeviceInfo, status) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GFSDK_Aftermath_GpuCrashDump_SystemInfo {
    pub osVersion: [::core::ffi::c_char; 128usize],
    pub displayDriver: GFSDK_Aftermath_GpuCrashDump_SystemInfo_DisplayDriverVersion,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GFSDK_Aftermath_GpuCrashDump_SystemInfo_DisplayDriverVersion {
    pub major: u32,
    pub minor: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_GpuCrashDump_SystemInfo_DisplayDriverVersion"][::core::mem::size_of::<
        GFSDK_Aftermath_GpuCrashDump_SystemInfo_DisplayDriverVersion,
    >() - 8usize];
    ["Alignment of GFSDK_Aftermath_GpuCrashDump_SystemInfo_DisplayDriverVersion"]
        [::core::mem::align_of::<GFSDK_Aftermath_GpuCrashDump_SystemInfo_DisplayDriverVersion>()
            - 4usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_SystemInfo_DisplayDriverVersion::major"][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_SystemInfo_DisplayDriverVersion,
        major
    )
        - 0usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_SystemInfo_DisplayDriverVersion::minor"][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_SystemInfo_DisplayDriverVersion,
        minor
    )
        - 4usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_GpuCrashDump_SystemInfo"]
        [::core::mem::size_of::<GFSDK_Aftermath_GpuCrashDump_SystemInfo>() - 136usize];
    ["Alignment of GFSDK_Aftermath_GpuCrashDump_SystemInfo"]
        [::core::mem::align_of::<GFSDK_Aftermath_GpuCrashDump_SystemInfo>() - 4usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_SystemInfo::osVersion"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_SystemInfo, osVersion) - 0usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_SystemInfo::displayDriver"][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_SystemInfo,
        displayDriver
    ) - 128usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GFSDK_Aftermath_GpuCrashDump_GpuInfo {
    pub adapterName: [::core::ffi::c_char; 128usize],
    pub generationName: [::core::ffi::c_char; 128usize],
    pub adapterLUID: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_GpuCrashDump_GpuInfo"]
        [::core::mem::size_of::<GFSDK_Aftermath_GpuCrashDump_GpuInfo>() - 264usize];
    ["Alignment of GFSDK_Aftermath_GpuCrashDump_GpuInfo"]
        [::core::mem::align_of::<GFSDK_Aftermath_GpuCrashDump_GpuInfo>() - 8usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_GpuInfo::adapterName"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_GpuInfo, adapterName) - 0usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_GpuInfo::generationName"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_GpuInfo, generationName) - 128usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_GpuInfo::adapterLUID"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_GpuInfo, adapterLUID) - 256usize];
};
pub type GFSDK_Aftermath_FaultType = u32;
pub const GFSDK_Aftermath_FaultType_GFSDK_Aftermath_FaultType_Unknown: GFSDK_Aftermath_FaultType =
    0;
pub const GFSDK_Aftermath_FaultType_GFSDK_Aftermath_FaultType_AddressTranslationError:
    GFSDK_Aftermath_FaultType = 1;
pub const GFSDK_Aftermath_FaultType_GFSDK_Aftermath_FaultType_IllegalAccessError:
    GFSDK_Aftermath_FaultType = 2;
pub type GFSDK_Aftermath_AccessType = u32;
pub const GFSDK_Aftermath_AccessType_GFSDK_Aftermath_AccessType_Unknown:
    GFSDK_Aftermath_AccessType = 0;
pub const GFSDK_Aftermath_AccessType_GFSDK_Aftermath_AccessType_Read: GFSDK_Aftermath_AccessType =
    1;
pub const GFSDK_Aftermath_AccessType_GFSDK_Aftermath_AccessType_Write: GFSDK_Aftermath_AccessType =
    2;
pub const GFSDK_Aftermath_AccessType_GFSDK_Aftermath_AccessType_Atomic: GFSDK_Aftermath_AccessType =
    3;
pub type GFSDK_Aftermath_Engine = u32;
pub const GFSDK_Aftermath_Engine_GFSDK_Aftermath_Engine_Unknown: GFSDK_Aftermath_Engine = 0;
pub const GFSDK_Aftermath_Engine_GFSDK_Aftermath_Engine_Graphics: GFSDK_Aftermath_Engine = 1;
pub const GFSDK_Aftermath_Engine_GFSDK_Aftermath_Engine_GraphicsCompute: GFSDK_Aftermath_Engine = 2;
pub const GFSDK_Aftermath_Engine_GFSDK_Aftermath_Engine_Display: GFSDK_Aftermath_Engine = 3;
pub const GFSDK_Aftermath_Engine_GFSDK_Aftermath_Engine_CopyEngine: GFSDK_Aftermath_Engine = 4;
pub const GFSDK_Aftermath_Engine_GFSDK_Aftermath_Engine_VideoDecoder: GFSDK_Aftermath_Engine = 5;
pub const GFSDK_Aftermath_Engine_GFSDK_Aftermath_Engine_VideoEncoder: GFSDK_Aftermath_Engine = 6;
pub const GFSDK_Aftermath_Engine_GFSDK_Aftermath_Engine_Other: GFSDK_Aftermath_Engine = 7;
pub type GFSDK_Aftermath_Client = u32;
pub const GFSDK_Aftermath_Client_GFSDK_Aftermath_Client_Unknown: GFSDK_Aftermath_Client = 0;
pub const GFSDK_Aftermath_Client_GFSDK_Aftermath_Client_HostInterface: GFSDK_Aftermath_Client = 1;
pub const GFSDK_Aftermath_Client_GFSDK_Aftermath_Client_FrontEnd: GFSDK_Aftermath_Client = 2;
pub const GFSDK_Aftermath_Client_GFSDK_Aftermath_Client_PrimitiveDistributor:
    GFSDK_Aftermath_Client = 3;
pub const GFSDK_Aftermath_Client_GFSDK_Aftermath_Client_GraphicsProcessingCluster:
    GFSDK_Aftermath_Client = 4;
pub const GFSDK_Aftermath_Client_GFSDK_Aftermath_Client_PolymorphEngine: GFSDK_Aftermath_Client = 5;
pub const GFSDK_Aftermath_Client_GFSDK_Aftermath_Client_RasterEngine: GFSDK_Aftermath_Client = 6;
pub const GFSDK_Aftermath_Client_GFSDK_Aftermath_Client_Rasterizer2D: GFSDK_Aftermath_Client = 7;
pub const GFSDK_Aftermath_Client_GFSDK_Aftermath_Client_RenderOutputUnit: GFSDK_Aftermath_Client =
    8;
pub const GFSDK_Aftermath_Client_GFSDK_Aftermath_Client_TextureProcessingCluster:
    GFSDK_Aftermath_Client = 9;
pub const GFSDK_Aftermath_Client_GFSDK_Aftermath_Client_CopyEngine: GFSDK_Aftermath_Client = 10;
pub const GFSDK_Aftermath_Client_GFSDK_Aftermath_Client_VideoDecoder: GFSDK_Aftermath_Client = 11;
pub const GFSDK_Aftermath_Client_GFSDK_Aftermath_Client_VideoEncoder: GFSDK_Aftermath_Client = 12;
pub const GFSDK_Aftermath_Client_GFSDK_Aftermath_Client_Other: GFSDK_Aftermath_Client = 13;
pub type GFSDK_Aftermath_ResourceResidency = u32;
pub const GFSDK_Aftermath_ResourceResidency_GFSDK_Aftermath_ResourceResidency_Unknown:
    GFSDK_Aftermath_ResourceResidency = 0;
pub const GFSDK_Aftermath_ResourceResidency_GFSDK_Aftermath_ResourceResidency_FullyResident:
    GFSDK_Aftermath_ResourceResidency = 1;
pub const GFSDK_Aftermath_ResourceResidency_GFSDK_Aftermath_ResourceResidency_Evicted:
    GFSDK_Aftermath_ResourceResidency = 2;
pub const GFSDK_Aftermath_ResourceResidency_GFSDK_Aftermath_ResourceResidency_MemoryFreed:
    GFSDK_Aftermath_ResourceResidency = 3;
pub const GFSDK_Aftermath_ResourceResidency_GFSDK_Aftermath_ResourceResidency_MemoryUnbound:
    GFSDK_Aftermath_ResourceResidency = 4;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GFSDK_Aftermath_GpuCrashDump_PageFaultInfo {
    pub faultingGpuVA: u64,
    pub faultType: GFSDK_Aftermath_FaultType,
    pub accessType: GFSDK_Aftermath_AccessType,
    pub engine: GFSDK_Aftermath_Engine,
    pub client: GFSDK_Aftermath_Client,
    pub resourceInfoCount: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_GpuCrashDump_PageFaultInfo"]
        [::core::mem::size_of::<GFSDK_Aftermath_GpuCrashDump_PageFaultInfo>() - 32usize];
    ["Alignment of GFSDK_Aftermath_GpuCrashDump_PageFaultInfo"]
        [::core::mem::align_of::<GFSDK_Aftermath_GpuCrashDump_PageFaultInfo>() - 8usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_PageFaultInfo::faultingGpuVA"][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_PageFaultInfo,
        faultingGpuVA
    ) - 0usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_PageFaultInfo::faultType"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_PageFaultInfo, faultType) - 8usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_PageFaultInfo::accessType"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_PageFaultInfo, accessType) - 12usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_PageFaultInfo::engine"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_PageFaultInfo, engine) - 16usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_PageFaultInfo::client"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_PageFaultInfo, client) - 20usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_PageFaultInfo::resourceInfoCount"][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_PageFaultInfo,
        resourceInfoCount
    ) - 24usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct GFSDK_Aftermath_GpuCrashDump_ResourceInfo {
    pub gpuVa: u64,
    pub size: u64,
    pub width: u32,
    pub height: u32,
    pub depth: u32,
    pub mipLevels: u32,
    pub format: u32,
    pub apiResource: u64,
    pub debugName: [::core::ffi::c_char; 128usize],
    pub __bindgen_anon_1: GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_1,
    pub __bindgen_anon_2: GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_2,
    pub __bindgen_anon_3: GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_3,
    pub __bindgen_anon_4: GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_4,
    pub __bindgen_anon_5: GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_5,
    pub residency: GFSDK_Aftermath_ResourceResidency,
    pub createDestroyTickCount: u32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_1 {
    pub bIsBufferHeap: bool,
    pub bool_align_bIsBufferHeap: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_1"][::core::mem::size_of::<
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_1,
    >() - 4usize];
    ["Alignment of GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_1"][::core::mem::align_of::<
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_1,
    >() - 4usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_1::bIsBufferHeap"][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_1,
        bIsBufferHeap
    )
        - 0usize];
    [
        "Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_1::bool_align_bIsBufferHeap",
    ][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_1,
        bool_align_bIsBufferHeap
    ) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_2 {
    pub bIsStaticTextureHeap: bool,
    pub bool_align_bIsStaticTextureHeap: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_2"][::core::mem::size_of::<
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_2,
    >() - 4usize];
    ["Alignment of GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_2"][::core::mem::align_of::<
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_2,
    >() - 4usize];
    [
        "Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_2::bIsStaticTextureHeap",
    ][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_2,
        bIsStaticTextureHeap
    ) - 0usize];
    [
        "Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_2::bool_align_bIsStaticTextureHeap",
    ][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_2,
        bool_align_bIsStaticTextureHeap
    ) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_3 {
    pub bIsRenderTargetOrDepthStencilViewHeap: bool,
    pub bool_align_bIsRenderTargetOrDepthStencilViewHeap: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_3"][::core::mem::size_of::<
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_3,
    >() - 4usize];
    ["Alignment of GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_3"][::core::mem::align_of::<
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_3,
    >() - 4usize];
    [
        "Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_3::bIsRenderTargetOrDepthStencilViewHeap",
    ][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_3,
        bIsRenderTargetOrDepthStencilViewHeap
    ) - 0usize];
    [
        "Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_3::bool_align_bIsRenderTargetOrDepthStencilViewHeap",
    ][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_3,
        bool_align_bIsRenderTargetOrDepthStencilViewHeap
    ) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_4 {
    pub bPlacedResource: bool,
    pub bool_align_bPlacedResource: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_4"][::core::mem::size_of::<
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_4,
    >() - 4usize];
    ["Alignment of GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_4"][::core::mem::align_of::<
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_4,
    >() - 4usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_4::bPlacedResource"][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_4,
        bPlacedResource
    )
        - 0usize];
    [
        "Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_4::bool_align_bPlacedResource",
    ][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_4,
        bool_align_bPlacedResource
    ) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_5 {
    pub bWasDestroyed: bool,
    pub bool_align_bWasDestroyed: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_5"][::core::mem::size_of::<
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_5,
    >() - 4usize];
    ["Alignment of GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_5"][::core::mem::align_of::<
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_5,
    >() - 4usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_5::bWasDestroyed"][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_5,
        bWasDestroyed
    )
        - 0usize];
    [
        "Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_5::bool_align_bWasDestroyed",
    ][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo__bindgen_ty_5,
        bool_align_bWasDestroyed
    ) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_GpuCrashDump_ResourceInfo"]
        [::core::mem::size_of::<GFSDK_Aftermath_GpuCrashDump_ResourceInfo>() - 208usize];
    ["Alignment of GFSDK_Aftermath_GpuCrashDump_ResourceInfo"]
        [::core::mem::align_of::<GFSDK_Aftermath_GpuCrashDump_ResourceInfo>() - 8usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo::gpuVa"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_ResourceInfo, gpuVa) - 0usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo::size"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_ResourceInfo, size) - 8usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo::width"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_ResourceInfo, width) - 16usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo::height"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_ResourceInfo, height) - 20usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo::depth"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_ResourceInfo, depth) - 24usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo::mipLevels"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_ResourceInfo, mipLevels) - 28usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo::format"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_ResourceInfo, format) - 32usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo::apiResource"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_ResourceInfo, apiResource) - 40usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo::debugName"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_ResourceInfo, debugName) - 48usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo::residency"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_ResourceInfo, residency) - 196usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_ResourceInfo::createDestroyTickCount"][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_ResourceInfo,
        createDestroyTickCount
    )
        - 200usize];
};
pub type GFSDK_Aftermath_ShaderType = u32;
pub const GFSDK_Aftermath_ShaderType_GFSDK_Aftermath_ShaderType_Unknown:
    GFSDK_Aftermath_ShaderType = 0;
pub const GFSDK_Aftermath_ShaderType_GFSDK_Aftermath_ShaderType_Vertex: GFSDK_Aftermath_ShaderType =
    1;
pub const GFSDK_Aftermath_ShaderType_GFSDK_Aftermath_ShaderType_Tessellation_Control:
    GFSDK_Aftermath_ShaderType = 2;
pub const GFSDK_Aftermath_ShaderType_GFSDK_Aftermath_ShaderType_Hull: GFSDK_Aftermath_ShaderType =
    2;
pub const GFSDK_Aftermath_ShaderType_GFSDK_Aftermath_ShaderType_Tessellation_Evaluation:
    GFSDK_Aftermath_ShaderType = 3;
pub const GFSDK_Aftermath_ShaderType_GFSDK_Aftermath_ShaderType_Domain: GFSDK_Aftermath_ShaderType =
    3;
pub const GFSDK_Aftermath_ShaderType_GFSDK_Aftermath_ShaderType_Geometry:
    GFSDK_Aftermath_ShaderType = 4;
pub const GFSDK_Aftermath_ShaderType_GFSDK_Aftermath_ShaderType_Fragment:
    GFSDK_Aftermath_ShaderType = 5;
pub const GFSDK_Aftermath_ShaderType_GFSDK_Aftermath_ShaderType_Pixel: GFSDK_Aftermath_ShaderType =
    5;
pub const GFSDK_Aftermath_ShaderType_GFSDK_Aftermath_ShaderType_Compute:
    GFSDK_Aftermath_ShaderType = 6;
pub const GFSDK_Aftermath_ShaderType_GFSDK_Aftermath_ShaderType_RayTracing_RayGeneration:
    GFSDK_Aftermath_ShaderType = 7;
pub const GFSDK_Aftermath_ShaderType_GFSDK_Aftermath_ShaderType_RayTracing_Miss:
    GFSDK_Aftermath_ShaderType = 8;
pub const GFSDK_Aftermath_ShaderType_GFSDK_Aftermath_ShaderType_RayTracing_Intersection:
    GFSDK_Aftermath_ShaderType = 9;
pub const GFSDK_Aftermath_ShaderType_GFSDK_Aftermath_ShaderType_RayTracing_AnyHit:
    GFSDK_Aftermath_ShaderType = 10;
pub const GFSDK_Aftermath_ShaderType_GFSDK_Aftermath_ShaderType_RayTracing_ClosestHit:
    GFSDK_Aftermath_ShaderType = 11;
pub const GFSDK_Aftermath_ShaderType_GFSDK_Aftermath_ShaderType_RayTracing_Callable:
    GFSDK_Aftermath_ShaderType = 12;
pub const GFSDK_Aftermath_ShaderType_GFSDK_Aftermath_ShaderType_RayTracing_Internal:
    GFSDK_Aftermath_ShaderType = 13;
pub const GFSDK_Aftermath_ShaderType_GFSDK_Aftermath_ShaderType_Mesh: GFSDK_Aftermath_ShaderType =
    14;
pub const GFSDK_Aftermath_ShaderType_GFSDK_Aftermath_ShaderType_Task: GFSDK_Aftermath_ShaderType =
    15;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct GFSDK_Aftermath_GpuCrashDump_ShaderInfo {
    pub shaderHash: u64,
    pub shaderDebugInfoUid: u64,
    pub __bindgen_anon_1: GFSDK_Aftermath_GpuCrashDump_ShaderInfo__bindgen_ty_1,
    pub shaderType: GFSDK_Aftermath_ShaderType,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union GFSDK_Aftermath_GpuCrashDump_ShaderInfo__bindgen_ty_1 {
    pub isInternal: bool,
    pub bool_align_isInternal: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_GpuCrashDump_ShaderInfo__bindgen_ty_1"]
        [::core::mem::size_of::<GFSDK_Aftermath_GpuCrashDump_ShaderInfo__bindgen_ty_1>() - 4usize];
    ["Alignment of GFSDK_Aftermath_GpuCrashDump_ShaderInfo__bindgen_ty_1"]
        [::core::mem::align_of::<GFSDK_Aftermath_GpuCrashDump_ShaderInfo__bindgen_ty_1>() - 4usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_ShaderInfo__bindgen_ty_1::isInternal"][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_ShaderInfo__bindgen_ty_1,
        isInternal
    )
        - 0usize];
    [
        "Offset of field: GFSDK_Aftermath_GpuCrashDump_ShaderInfo__bindgen_ty_1::bool_align_isInternal",
    ][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_ShaderInfo__bindgen_ty_1,
        bool_align_isInternal
    ) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_GpuCrashDump_ShaderInfo"]
        [::core::mem::size_of::<GFSDK_Aftermath_GpuCrashDump_ShaderInfo>() - 24usize];
    ["Alignment of GFSDK_Aftermath_GpuCrashDump_ShaderInfo"]
        [::core::mem::align_of::<GFSDK_Aftermath_GpuCrashDump_ShaderInfo>() - 8usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_ShaderInfo::shaderHash"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_ShaderInfo, shaderHash) - 0usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_ShaderInfo::shaderDebugInfoUid"][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_ShaderInfo,
        shaderDebugInfoUid
    ) - 8usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_ShaderInfo::shaderType"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_ShaderInfo, shaderType) - 20usize];
};
pub type GFSDK_Aftermath_Context_Type = u32;
pub const GFSDK_Aftermath_Context_Type_GFSDK_Aftermath_Context_Type_Invalid:
    GFSDK_Aftermath_Context_Type = 0;
pub const GFSDK_Aftermath_Context_Type_GFSDK_Aftermath_Context_Type_Immediate:
    GFSDK_Aftermath_Context_Type = 1;
pub const GFSDK_Aftermath_Context_Type_GFSDK_Aftermath_Context_Type_CommandList:
    GFSDK_Aftermath_Context_Type = 2;
pub const GFSDK_Aftermath_Context_Type_GFSDK_Aftermath_Context_Type_Bundle:
    GFSDK_Aftermath_Context_Type = 3;
pub const GFSDK_Aftermath_Context_Type_GFSDK_Aftermath_Context_Type_CommandQueue:
    GFSDK_Aftermath_Context_Type = 4;
pub type GFSDK_Aftermath_EventMarkerDataOwnership = u32;
pub const GFSDK_Aftermath_EventMarkerDataOwnership_GFSDK_Aftermath_EventMarkerDataOwnership_User:
    GFSDK_Aftermath_EventMarkerDataOwnership = 0;
pub const GFSDK_Aftermath_EventMarkerDataOwnership_GFSDK_Aftermath_EventMarkerDataOwnership_Decoder : GFSDK_Aftermath_EventMarkerDataOwnership = 1 ;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo {
    pub contextId: u64,
    pub contextStatus: GFSDK_Aftermath_Context_Status,
    pub contextType: GFSDK_Aftermath_Context_Type,
    pub __bindgen_anon_1: GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo__bindgen_ty_1,
    pub markerDataOwnership: GFSDK_Aftermath_EventMarkerDataOwnership,
    pub markerDataSize: u32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo__bindgen_ty_1 {
    pub markerData: *const ::core::ffi::c_void,
    pub ptr_align_markerData: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo__bindgen_ty_1"][::core::mem::size_of::<
        GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo__bindgen_ty_1,
    >() - 8usize];
    ["Alignment of GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo__bindgen_ty_1"]
        [::core::mem::align_of::<GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo__bindgen_ty_1>()
            - 8usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo__bindgen_ty_1::markerData"][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo__bindgen_ty_1,
        markerData
    )
        - 0usize];
    [
        "Offset of field: GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo__bindgen_ty_1::ptr_align_markerData",
    ][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo__bindgen_ty_1,
        ptr_align_markerData
    ) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo"]
        [::core::mem::size_of::<GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo>() - 32usize];
    ["Alignment of GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo"]
        [::core::mem::align_of::<GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo>() - 8usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo::contextId"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo, contextId) - 0usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo::contextStatus"][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo,
        contextStatus
    ) - 8usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo::contextType"][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo,
        contextType
    ) - 12usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo::markerDataOwnership"][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo,
        markerDataOwnership
    )
        - 24usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo::markerDataSize"][::core::mem::offset_of!(
        GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo,
        markerDataSize
    ) - 28usize];
};
pub type GFSDK_Aftermath_GpuCrashDumpDecoderFlags = u32;
pub const GFSDK_Aftermath_GpuCrashDumpDecoderFlags_GFSDK_Aftermath_GpuCrashDumpDecoderFlags_BASE_INFO : GFSDK_Aftermath_GpuCrashDumpDecoderFlags = 1 ;
pub const GFSDK_Aftermath_GpuCrashDumpDecoderFlags_GFSDK_Aftermath_GpuCrashDumpDecoderFlags_DEVICE_INFO : GFSDK_Aftermath_GpuCrashDumpDecoderFlags = 2 ;
pub const GFSDK_Aftermath_GpuCrashDumpDecoderFlags_GFSDK_Aftermath_GpuCrashDumpDecoderFlags_OS_INFO : GFSDK_Aftermath_GpuCrashDumpDecoderFlags = 4 ;
pub const GFSDK_Aftermath_GpuCrashDumpDecoderFlags_GFSDK_Aftermath_GpuCrashDumpDecoderFlags_DISPLAY_DRIVER_INFO : GFSDK_Aftermath_GpuCrashDumpDecoderFlags = 8 ;
pub const GFSDK_Aftermath_GpuCrashDumpDecoderFlags_GFSDK_Aftermath_GpuCrashDumpDecoderFlags_GPU_INFO : GFSDK_Aftermath_GpuCrashDumpDecoderFlags = 16 ;
pub const GFSDK_Aftermath_GpuCrashDumpDecoderFlags_GFSDK_Aftermath_GpuCrashDumpDecoderFlags_PAGE_FAULT_INFO : GFSDK_Aftermath_GpuCrashDumpDecoderFlags = 32 ;
pub const GFSDK_Aftermath_GpuCrashDumpDecoderFlags_GFSDK_Aftermath_GpuCrashDumpDecoderFlags_SHADER_INFO : GFSDK_Aftermath_GpuCrashDumpDecoderFlags = 64 ;
pub const GFSDK_Aftermath_GpuCrashDumpDecoderFlags_GFSDK_Aftermath_GpuCrashDumpDecoderFlags_WARP_STATE_INFO : GFSDK_Aftermath_GpuCrashDumpDecoderFlags = 128 ;
pub const GFSDK_Aftermath_GpuCrashDumpDecoderFlags_GFSDK_Aftermath_GpuCrashDumpDecoderFlags_SHADER_MAPPING_INFO : GFSDK_Aftermath_GpuCrashDumpDecoderFlags = 256 ;
pub const GFSDK_Aftermath_GpuCrashDumpDecoderFlags_GFSDK_Aftermath_GpuCrashDumpDecoderFlags_EVENT_MARKER_INFO : GFSDK_Aftermath_GpuCrashDumpDecoderFlags = 512 ;
pub const GFSDK_Aftermath_GpuCrashDumpDecoderFlags_GFSDK_Aftermath_GpuCrashDumpDecoderFlags_CALL_STACK_INFO : GFSDK_Aftermath_GpuCrashDumpDecoderFlags = 1024 ;
pub const GFSDK_Aftermath_GpuCrashDumpDecoderFlags_GFSDK_Aftermath_GpuCrashDumpDecoderFlags_DESCRIPTION_INFO : GFSDK_Aftermath_GpuCrashDumpDecoderFlags = 2048 ;
pub const GFSDK_Aftermath_GpuCrashDumpDecoderFlags_GFSDK_Aftermath_GpuCrashDumpDecoderFlags_FAULTED_WARP_INFO : GFSDK_Aftermath_GpuCrashDumpDecoderFlags = 4096 ;
pub const GFSDK_Aftermath_GpuCrashDumpDecoderFlags_GFSDK_Aftermath_GpuCrashDumpDecoderFlags_FINGERPRINT_INFO : GFSDK_Aftermath_GpuCrashDumpDecoderFlags = 8192 ;
pub const GFSDK_Aftermath_GpuCrashDumpDecoderFlags_GFSDK_Aftermath_GpuCrashDumpDecoderFlags_ALL_INFO : GFSDK_Aftermath_GpuCrashDumpDecoderFlags = 16383 ;
pub type GFSDK_Aftermath_GpuCrashDumpFormatterFlags = u32;
pub const GFSDK_Aftermath_GpuCrashDumpFormatterFlags_GFSDK_Aftermath_GpuCrashDumpFormatterFlags_NONE : GFSDK_Aftermath_GpuCrashDumpFormatterFlags = 0 ;
pub const GFSDK_Aftermath_GpuCrashDumpFormatterFlags_GFSDK_Aftermath_GpuCrashDumpFormatterFlags_CONDENSED_OUTPUT : GFSDK_Aftermath_GpuCrashDumpFormatterFlags = 1 ;
pub const GFSDK_Aftermath_GpuCrashDumpFormatterFlags_GFSDK_Aftermath_GpuCrashDumpFormatterFlags_UTF8_OUTPUT : GFSDK_Aftermath_GpuCrashDumpFormatterFlags = 2 ;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct GFSDK_Aftermath_GpuCrashDump_Decoder__ {
    pub ID: i32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GFSDK_Aftermath_GpuCrashDump_Decoder__"]
        [::core::mem::size_of::<GFSDK_Aftermath_GpuCrashDump_Decoder__>() - 4usize];
    ["Alignment of GFSDK_Aftermath_GpuCrashDump_Decoder__"]
        [::core::mem::align_of::<GFSDK_Aftermath_GpuCrashDump_Decoder__>() - 4usize];
    ["Offset of field: GFSDK_Aftermath_GpuCrashDump_Decoder__::ID"]
        [::core::mem::offset_of!(GFSDK_Aftermath_GpuCrashDump_Decoder__, ID) - 0usize];
};
pub type GFSDK_Aftermath_GpuCrashDump_Decoder = *mut GFSDK_Aftermath_GpuCrashDump_Decoder__;
pub type PFN_GFSDK_Aftermath_SetData =
    ::core::option::Option<unsafe extern "C" fn(pData: *const ::core::ffi::c_void, size: u32)>;
pub type PFN_GFSDK_Aftermath_ShaderDebugInfoLookupCb = ::core::option::Option<
    unsafe extern "C" fn(
        pIdentifier: *const GFSDK_Aftermath_ShaderDebugInfoIdentifier,
        setShaderDebugInfo: PFN_GFSDK_Aftermath_SetData,
        pUserData: *mut ::core::ffi::c_void,
    ),
>;
pub type PFN_GFSDK_Aftermath_ShaderLookupCb = ::core::option::Option<
    unsafe extern "C" fn(
        pShaderHash: *const GFSDK_Aftermath_ShaderBinaryHash,
        setShaderBinary: PFN_GFSDK_Aftermath_SetData,
        pUserData: *mut ::core::ffi::c_void,
    ),
>;
pub type PFN_GFSDK_Aftermath_ShaderSourceDebugInfoLookupCb = ::core::option::Option<
    unsafe extern "C" fn(
        pShaderDebugName: *const GFSDK_Aftermath_ShaderDebugName,
        setShaderBinary: PFN_GFSDK_Aftermath_SetData,
        pUserData: *mut ::core::ffi::c_void,
    ),
>;
unsafe extern "C" {
    pub fn GFSDK_Aftermath_GpuCrashDump_CreateDecoder(
        apiVersion: GFSDK_Aftermath_Version,
        pGpuCrashDump: *const ::core::ffi::c_void,
        gpuCrashDumpSize: u32,
        pDecoder: *mut GFSDK_Aftermath_GpuCrashDump_Decoder,
    ) -> GFSDK_Aftermath_Result;
}
unsafe extern "C" {
    pub fn GFSDK_Aftermath_GpuCrashDump_DestroyDecoder(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
    ) -> GFSDK_Aftermath_Result;
}
unsafe extern "C" {
    pub fn GFSDK_Aftermath_GpuCrashDump_GetBaseInfo(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        pBaseInfo: *mut GFSDK_Aftermath_GpuCrashDump_BaseInfo,
    ) -> GFSDK_Aftermath_Result;
}
unsafe extern "C" {
    pub fn GFSDK_Aftermath_GpuCrashDump_GetDescriptionSize(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        key: u32,
        pValueSize: *mut u32,
    ) -> GFSDK_Aftermath_Result;
}
unsafe extern "C" {
    pub fn GFSDK_Aftermath_GpuCrashDump_GetDescription(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        key: u32,
        valueBufferSize: u32,
        pValue: *mut ::core::ffi::c_char,
    ) -> GFSDK_Aftermath_Result;
}
unsafe extern "C" {
    pub fn GFSDK_Aftermath_GpuCrashDump_GetDeviceInfo(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        pDeviceInfo: *mut GFSDK_Aftermath_GpuCrashDump_DeviceInfo,
    ) -> GFSDK_Aftermath_Result;
}
unsafe extern "C" {
    pub fn GFSDK_Aftermath_GpuCrashDump_GetSystemInfo(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        pSystemInfo: *mut GFSDK_Aftermath_GpuCrashDump_SystemInfo,
    ) -> GFSDK_Aftermath_Result;
}
unsafe extern "C" {
    pub fn GFSDK_Aftermath_GpuCrashDump_GetGpuInfoCount(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        pGpuCount: *mut u32,
    ) -> GFSDK_Aftermath_Result;
}
unsafe extern "C" {
    pub fn GFSDK_Aftermath_GpuCrashDump_GetGpuInfo(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        gpuInfoBufferCount: u32,
        pGpuInfo: *mut GFSDK_Aftermath_GpuCrashDump_GpuInfo,
    ) -> GFSDK_Aftermath_Result;
}
unsafe extern "C" {
    pub fn GFSDK_Aftermath_GpuCrashDump_GetPageFaultInfo(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        pPageFaultInfo: *mut GFSDK_Aftermath_GpuCrashDump_PageFaultInfo,
    ) -> GFSDK_Aftermath_Result;
}
unsafe extern "C" {
    pub fn GFSDK_Aftermath_GpuCrashDump_GetPageFaultResourceInfo(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        resourceInfoCount: u32,
        pResourceInfo: *mut GFSDK_Aftermath_GpuCrashDump_ResourceInfo,
    ) -> GFSDK_Aftermath_Result;
}
unsafe extern "C" {
    pub fn GFSDK_Aftermath_GpuCrashDump_GetActiveShadersInfoCount(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        pShaderCount: *mut u32,
    ) -> GFSDK_Aftermath_Result;
}
unsafe extern "C" {
    pub fn GFSDK_Aftermath_GpuCrashDump_GetActiveShadersInfo(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        shaderInfoBufferCount: u32,
        pShaderInfo: *mut GFSDK_Aftermath_GpuCrashDump_ShaderInfo,
    ) -> GFSDK_Aftermath_Result;
}
unsafe extern "C" {
    pub fn GFSDK_Aftermath_GpuCrashDump_GetEventMarkersInfoCount(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        pMarkerCount: *mut u32,
    ) -> GFSDK_Aftermath_Result;
}
unsafe extern "C" {
    pub fn GFSDK_Aftermath_GpuCrashDump_GetEventMarkersInfo(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        markerInfoBufferCount: u32,
        pMarkerInfo: *mut GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo,
    ) -> GFSDK_Aftermath_Result;
}
unsafe extern "C" {
    pub fn GFSDK_Aftermath_GpuCrashDump_GenerateJSON(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        decoderFlags: u32,
        formatFlags: u32,
        shaderDebugInfoLookupCb: PFN_GFSDK_Aftermath_ShaderDebugInfoLookupCb,
        shaderLookupCb: PFN_GFSDK_Aftermath_ShaderLookupCb,
        shaderSourceDebugInfoLookupCb: PFN_GFSDK_Aftermath_ShaderSourceDebugInfoLookupCb,
        pUserData: *mut ::core::ffi::c_void,
        pJsonSize: *mut u32,
    ) -> GFSDK_Aftermath_Result;
}
unsafe extern "C" {
    pub fn GFSDK_Aftermath_GpuCrashDump_GetJSON(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        jsonBufferSize: u32,
        pJson: *mut ::core::ffi::c_char,
    ) -> GFSDK_Aftermath_Result;
}
unsafe extern "C" {
    pub fn GFSDK_Aftermath_GetShaderDebugInfoIdentifier(
        apiVersion: GFSDK_Aftermath_Version,
        pShaderDebugInfo: *const ::core::ffi::c_void,
        shaderDebugInfoSize: u32,
        pIdentifier: *mut GFSDK_Aftermath_ShaderDebugInfoIdentifier,
    ) -> GFSDK_Aftermath_Result;
}
unsafe extern "C" {
    pub fn GFSDK_Aftermath_GetShaderHashForShaderInfo(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        pShaderInfo: *const GFSDK_Aftermath_GpuCrashDump_ShaderInfo,
        pShaderHash: *mut GFSDK_Aftermath_ShaderBinaryHash,
    ) -> GFSDK_Aftermath_Result;
}
pub type PFN_GFSDK_Aftermath_GpuCrashDump_CreateDecoder = ::core::option::Option<
    unsafe extern "C" fn(
        apiVersion: GFSDK_Aftermath_Version,
        pGpuCrashDump: *const ::core::ffi::c_void,
        gpuCrashDumpSize: u32,
        pDecoder: *mut GFSDK_Aftermath_GpuCrashDump_Decoder,
    ) -> GFSDK_Aftermath_Result,
>;
pub type PFN_GFSDK_Aftermath_GpuCrashDump_DestroyDecoder = ::core::option::Option<
    unsafe extern "C" fn(decoder: GFSDK_Aftermath_GpuCrashDump_Decoder) -> GFSDK_Aftermath_Result,
>;
pub type PFN_GFSDK_Aftermath_GpuCrashDump_GetBaseInfo = ::core::option::Option<
    unsafe extern "C" fn(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        pBaseInfo: *mut GFSDK_Aftermath_GpuCrashDump_BaseInfo,
    ) -> GFSDK_Aftermath_Result,
>;
pub type PFN_GFSDK_Aftermath_GpuCrashDump_GetDescriptionSize = ::core::option::Option<
    unsafe extern "C" fn(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        key: u32,
        pValueSize: *mut u32,
    ) -> GFSDK_Aftermath_Result,
>;
pub type PFN_GFSDK_Aftermath_GpuCrashDump_GetDescription = ::core::option::Option<
    unsafe extern "C" fn(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        key: u32,
        valueBufferSize: u32,
        pValue: *mut ::core::ffi::c_char,
    ) -> GFSDK_Aftermath_Result,
>;
pub type PFN_GFSDK_Aftermath_GpuCrashDump_GetDeviceInfo = ::core::option::Option<
    unsafe extern "C" fn(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        pDeviceInfo: *mut GFSDK_Aftermath_GpuCrashDump_DeviceInfo,
    ) -> GFSDK_Aftermath_Result,
>;
pub type PFN_GFSDK_Aftermath_GpuCrashDump_GetSystemInfo = ::core::option::Option<
    unsafe extern "C" fn(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        pSystemInfo: *mut GFSDK_Aftermath_GpuCrashDump_SystemInfo,
    ) -> GFSDK_Aftermath_Result,
>;
pub type PFN_GFSDK_Aftermath_GpuCrashDump_GetGpuInfoCount = ::core::option::Option<
    unsafe extern "C" fn(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        pGpuCount: *mut u32,
    ) -> GFSDK_Aftermath_Result,
>;
pub type PFN_GFSDK_Aftermath_GpuCrashDump_GetGpuInfo = ::core::option::Option<
    unsafe extern "C" fn(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        gpuInfoBufferCount: u32,
        pGpuInfo: *mut GFSDK_Aftermath_GpuCrashDump_GpuInfo,
    ) -> GFSDK_Aftermath_Result,
>;
pub type PFN_GFSDK_Aftermath_GpuCrashDump_GetPageFaultInfo = ::core::option::Option<
    unsafe extern "C" fn(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        pPageFaultInfo: *mut GFSDK_Aftermath_GpuCrashDump_PageFaultInfo,
    ) -> GFSDK_Aftermath_Result,
>;
pub type PFN_GFSDK_Aftermath_GpuCrashDump_GetPageFaultResourceInfo = ::core::option::Option<
    unsafe extern "C" fn(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        resourceInfoCount: u32,
        pResourceInfo: *mut GFSDK_Aftermath_GpuCrashDump_ResourceInfo,
    ) -> GFSDK_Aftermath_Result,
>;
pub type PFN_GFSDK_Aftermath_GpuCrashDump_GetActiveShadersInfoCount = ::core::option::Option<
    unsafe extern "C" fn(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        pShaderCount: *mut u32,
    ) -> GFSDK_Aftermath_Result,
>;
pub type PFN_GFSDK_Aftermath_GpuCrashDump_GetActiveShadersInfo = ::core::option::Option<
    unsafe extern "C" fn(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        shaderInfoBufferCount: u32,
        pShaderInfo: *mut GFSDK_Aftermath_GpuCrashDump_ShaderInfo,
    ) -> GFSDK_Aftermath_Result,
>;
pub type PFN_GFSDK_Aftermath_GpuCrashDump_GetEventMarkersInfoCount = ::core::option::Option<
    unsafe extern "C" fn(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        markerInfoBufferCount: u32,
    ) -> GFSDK_Aftermath_Result,
>;
pub type PFN_GFSDK_Aftermath_GpuCrashDump_GetEventMarkersInfo = ::core::option::Option<
    unsafe extern "C" fn(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        markerInfoBufferCount: u32,
        pMarkerInfo: *mut GFSDK_Aftermath_GpuCrashDump_EventMarkerInfo,
    ) -> GFSDK_Aftermath_Result,
>;
pub type PFN_GFSDK_Aftermath_GpuCrashDump_GenerateJSON = ::core::option::Option<
    unsafe extern "C" fn(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        decoderFlags: u32,
        formatFlags: u32,
        shaderDebugInfoLookupCb: PFN_GFSDK_Aftermath_ShaderDebugInfoLookupCb,
        shaderLookupCb: PFN_GFSDK_Aftermath_ShaderLookupCb,
        shaderSourceDebugInfoLookupCb: PFN_GFSDK_Aftermath_ShaderSourceDebugInfoLookupCb,
        pUserData: *mut ::core::ffi::c_void,
        pJsonSize: *mut u32,
    ) -> GFSDK_Aftermath_Result,
>;
pub type PFN_GFSDK_Aftermath_GpuCrashDump_GetJSON = ::core::option::Option<
    unsafe extern "C" fn(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        jsonBufferSize: u32,
        pJson: *mut ::core::ffi::c_char,
    ) -> GFSDK_Aftermath_Result,
>;
pub type PFN_GFSDK_Aftermath_GetShaderDebugInfoIdentifier = ::core::option::Option<
    unsafe extern "C" fn(
        apiVersion: GFSDK_Aftermath_Version,
        pShaderDebugInfo: *const ::core::ffi::c_void,
        shaderDebugInfoSize: u32,
        pIdentifier: *mut GFSDK_Aftermath_ShaderDebugInfoIdentifier,
    ) -> GFSDK_Aftermath_Result,
>;
pub type PFN_GFSDK_Aftermath_GetShaderHashForShaderInfo = ::core::option::Option<
    unsafe extern "C" fn(
        decoder: GFSDK_Aftermath_GpuCrashDump_Decoder,
        pShaderInfo: *const GFSDK_Aftermath_GpuCrashDump_ShaderInfo,
        pShaderHash: *mut GFSDK_Aftermath_ShaderBinaryHash,
    ) -> GFSDK_Aftermath_Result,
>;
